server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost/subtlechat?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1476154535@qwer
#mapper文件位置配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.trojan.two.dao: debug
